"""add unique constraint to modulo sigla

Revision ID: 0edaa5871a64
Revises: 1256ccea74d8
Create Date: 2026-05-20 12:14:45.661604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0edaa5871a64'
down_revision: Union[str, Sequence[str], None] = '1256ccea74d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'modulos', ['sigla'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modulos', type_='unique')
    # ### end Alembic commands ###
