"""feat: agregar campo obligatorio a control_documentacion

Revision ID: 15dfe880ff9e
Revises: 0eeda5a67bc8
Create Date: 2026-04-27 23:07:24.792752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15dfe880ff9e'
down_revision: Union[str, Sequence[str], None] = '0eeda5a67bc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('control_documentacion', sa.Column('obligatorio', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('control_documentacion', 'obligatorio')
    # ### end Alembic commands ###
