"""feat: agregar columna grado a docentes

Revision ID: 231054ca40aa
Revises: 6cd48da0e373
Create Date: 2026-06-13 15:38:14.980030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '231054ca40aa'
down_revision: Union[str, Sequence[str], None] = '6cd48da0e373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docentes', sa.Column('grado', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('docentes', 'grado')
    # ### end Alembic commands ###
