"""refactor: agregando campo foto para soporte de imagenes base64 en programas

Revision ID: 25c0a86c6c67
Revises: 0edaa5871a64
Create Date: 2026-05-20 15:49:58.870754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25c0a86c6c67'
down_revision: Union[str, Sequence[str], None] = '0edaa5871a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programas', sa.Column('foto', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programas', 'foto')
    # ### end Alembic commands ###
