"""feat: agregando campo duracion_minima_meses a tipo_programa

Revision ID: 3840a2ae470b
Revises: a20a8d0d1818
Create Date: 2026-05-21 15:05:19.391865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3840a2ae470b'
down_revision: Union[str, Sequence[str], None] = 'a20a8d0d1818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipos_programa', sa.Column('duracion_minima_meses', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tipos_programa', 'duracion_minima_meses')
    # ### end Alembic commands ###
