"""feat: agregar fecha_inicio_nuevo fecha_fin_nuevo a historial_modulo, nullable estado

Revision ID: 3b032e080033
Revises: 3bd2025c89d5
Create Date: 2026-06-29 15:48:33.399575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b032e080033'
down_revision: Union[str, Sequence[str], None] = '3bd2025c89d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historial_modulo', sa.Column('fecha_inicio_nuevo', sa.Date(), nullable=True))
    op.add_column('historial_modulo', sa.Column('fecha_fin_nuevo', sa.Date(), nullable=True))
    op.alter_column('historial_modulo', 'estado_anterior',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('historial_modulo', 'estado_nuevo',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('historial_modulo', 'estado_nuevo',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('historial_modulo', 'estado_anterior',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('historial_modulo', 'fecha_fin_nuevo')
    op.drop_column('historial_modulo', 'fecha_inicio_nuevo')
    # ### end Alembic commands ###
