"""feat: expandir ruta documental a 20 documentos y nuevos estados de contratacion

Revision ID: 3bd2025c89d5
Revises: fcf8c9d3811f
Create Date: 2026-06-29 14:43:50.252914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bd2025c89d5'
down_revision: Union[str, Sequence[str], None] = 'fcf8c9d3811f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contratacion_docente', 'estado',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('documentos_contratacion', 'tipo',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=80),
               existing_nullable=False)
    # ### end Alembic commands ###

    # Migrar estados existentes al nuevo esquema
    conn = op.get_bind()
    conn.execute(sa.text(
        "UPDATE contratacion_docente SET estado = 'verificacion' WHERE estado = 'en_curso'"
    ))
    # Migrar tipos de documentos antiguos a los nuevos
    conn.execute(sa.text(
        "UPDATE documentos_contratacion SET tipo = 'invitacion_dictar_modulo', orden = 7 WHERE tipo = 'invitacion'"
    ))
    conn.execute(sa.text(
        "UPDATE documentos_contratacion SET tipo = 'respuesta_invitacion', orden = 8 WHERE tipo = 'aceptacion'"
    ))
    conn.execute(sa.text(
        "UPDATE documentos_contratacion SET tipo = 'solicitud_contratacion_consultor', orden = 4 WHERE tipo = 'solicitud'"
    ))


def downgrade() -> None:
    """Downgrade schema."""
    # Revertir migración de datos
    conn = op.get_bind()
    conn.execute(sa.text(
        "UPDATE contratacion_docente SET estado = 'en_curso' WHERE estado = 'verificacion'"
    ))
    conn.execute(sa.text(
        "UPDATE documentos_contratacion SET tipo = 'invitacion', orden = 0 WHERE tipo = 'invitacion_dictar_modulo'"
    ))
    conn.execute(sa.text(
        "UPDATE documentos_contratacion SET tipo = 'aceptacion', orden = 1 WHERE tipo = 'respuesta_invitacion'"
    ))
    conn.execute(sa.text(
        "UPDATE documentos_contratacion SET tipo = 'solicitud', orden = 2 WHERE tipo = 'solicitud_contratacion_consultor'"
    ))

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documentos_contratacion', 'tipo',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('contratacion_docente', 'estado',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
