"""feat: agregar tablas roles, permisos, roles_permisos, usuarios, administrativos y FK id_usuario en alumnos y docentes

Revision ID: 6cde3a8177e7
Revises: 29ed0d4713b2
Create Date: 2026-07-09 10:19:41.985631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cde3a8177e7'
down_revision: Union[str, Sequence[str], None] = '29ed0d4713b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permisos',
    sa.Column('id_permiso', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_permiso'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_permisos_id_permiso'), 'permisos', ['id_permiso'], unique=False)
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_roles_id_rol'), 'roles', ['id_rol'], unique=False)
    op.create_table('roles_permisos',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('id_permiso', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_permiso'], ['permisos.id_permiso'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_rol', 'id_permiso')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email', 'id_rol', name='uq_email_rol')
    )
    op.create_index(op.f('ix_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False)
    op.create_table('administrativos',
    sa.Column('id_administrativo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ci', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('cargo', sa.String(length=50), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_administrativo'),
    sa.UniqueConstraint('ci')
    )
    op.create_index(op.f('ix_administrativos_id_administrativo'), 'administrativos', ['id_administrativo'], unique=False)
    op.add_column('alumnos', sa.Column('id_usuario', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('alumno_correo_key'), 'alumnos', type_='unique')
    op.create_foreign_key(None, 'alumnos', 'usuarios', ['id_usuario'], ['id_usuario'])
    op.add_column('docentes', sa.Column('id_usuario', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('docente_correo_key'), 'docentes', type_='unique')
    op.create_foreign_key(None, 'docentes', 'usuarios', ['id_usuario'], ['id_usuario'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'docentes', type_='foreignkey')
    op.create_unique_constraint(op.f('docente_correo_key'), 'docentes', ['correo'], postgresql_nulls_not_distinct=False)
    op.drop_column('docentes', 'id_usuario')
    op.drop_constraint(None, 'alumnos', type_='foreignkey')
    op.create_unique_constraint(op.f('alumno_correo_key'), 'alumnos', ['correo'], postgresql_nulls_not_distinct=False)
    op.drop_column('alumnos', 'id_usuario')
    op.drop_index(op.f('ix_administrativos_id_administrativo'), table_name='administrativos')
    op.drop_table('administrativos')
    op.drop_index(op.f('ix_usuarios_id_usuario'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('roles_permisos')
    op.drop_index(op.f('ix_roles_id_rol'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permisos_id_permiso'), table_name='permisos')
    op.drop_table('permisos')
    # ### end Alembic commands ###
