"""feat: agregar columna extension a docentes y actualizar validaciones

Revision ID: 880f059a5827
Revises: 231054ca40aa
Create Date: 2026-06-13 15:48:02.001093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '880f059a5827'
down_revision: Union[str, Sequence[str], None] = '231054ca40aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docentes', sa.Column('extension', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('docentes', 'extension')
    # ### end Alembic commands ###
