"""refactor: haciendo id_docente nullable en detalle_programa_modulo para auto-creacion de modulos en ediciones

Revision ID: 95d6af589510
Revises: 25c0a86c6c67
Create Date: 2026-05-20 17:48:02.882626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95d6af589510'
down_revision: Union[str, Sequence[str], None] = '25c0a86c6c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detalle_programa_modulo', 'id_docente',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detalle_programa_modulo', 'id_docente',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
