"""refactor: agregando campo foto a programa_version

Revision ID: a20a8d0d1818
Revises: 95d6af589510
Create Date: 2026-05-21 10:25:12.836384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a20a8d0d1818'
down_revision: Union[str, Sequence[str], None] = '95d6af589510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programas_version', sa.Column('foto', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programas_version', 'foto')
    # ### end Alembic commands ###
