"""feat: agregando campo es_historico a programa

Revision ID: da6feea8d568
Revises: 3840a2ae470b
Create Date: 2026-05-21 17:41:30.296150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da6feea8d568'
down_revision: Union[str, Sequence[str], None] = '3840a2ae470b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('programas', sa.Column('es_historico', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('programas', 'es_historico', server_default=None)


def downgrade() -> None:
    """Upgrade schema."""
    op.drop_column('programas', 'es_historico')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programas', 'es_historico')
    # ### end Alembic commands ###
