"""feat: add unique constraint on (id_programa_version_edicion, orden)

Revision ID: dbc9e2010d71
Revises: 568ebd27d3dd
Create Date: 2026-06-15 16:10:04.099407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbc9e2010d71'
down_revision: Union[str, Sequence[str], None] = '568ebd27d3dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_detalle_orden_edicion', 'detalle_programa_modulo', ['id_programa_version_edicion', 'orden'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_detalle_orden_edicion', 'detalle_programa_modulo', type_='unique')
    # ### end Alembic commands ###
