"""add fecha_inicio and fecha_fin to contratacion_docente

Revision ID: fcf8c9d3811f
Revises: e38df358372f
Create Date: 2026-06-27 21:20:34.811249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf8c9d3811f'
down_revision: Union[str, Sequence[str], None] = 'e38df358372f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contratacion_docente', sa.Column('fecha_inicio', sa.Date(), nullable=True))
    op.add_column('contratacion_docente', sa.Column('fecha_fin', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contratacion_docente', 'fecha_fin')
    op.drop_column('contratacion_docente', 'fecha_inicio')
    # ### end Alembic commands ###
