from models.tipo_programa import TipoPrograma
from models.programa import Programa
from models.programa_version import ProgramaVersion
from models.modulo import Modulo
from models.modalidad_academica import ModalidadAcademica
from models.programa_version_edicion import ProgramaVersionEdicion
from models.docente import Docente
from models.detalle_programa_modulo import DetalleProgramaModulo
from models.horario import Horario
from models.alumno import Alumno
from models.detalle_programa_alumno import DetalleProgramaAlumno
from models.requisito import Requisito
from models.control_documentacion import ControlDocumentacion
from models.historial_modulo import HistorialModulo
from models.tipo_descuento import TipoDescuento
from models.modalidad_tipo_descuento import ModalidadTipoDescuento
from models.tipo_descuento_requisito import TipoDescuentoRequisito
from models.contratacion_docente import ContratacionDocente
from models.documento_contratacion import DocumentoContratacion
from models.rol import Rol
from models.permiso import Permiso
from models.roles_permiso import RolesPermiso
from models.usuario import Usuario
from models.usuario_rol import UsuarioRol
from models.administrativo import Administrativo
from models.modalidad_tipo_programa import ModalidadTipoPrograma